### PR TITLE
added del()

### PR DESCRIPTION
**Pull request by pfrazee**
deletes an edge, emits a 'del' event if the data on the edge was not undefined

``` js
var g = new (require('graphmitter'))
g.edge(1,2).edge(2,1).del(1,2)
g.toJSON()
// => { '1': {}, '2': { '1': true } }
```

### CODE REVIEW

**Comment by pfraze** [comment]
nodes are not deleted if they have all edges removed. doing so would conserve space, but would result in more allocations/deletes (eg if the node is then used again). it's not hard to imagine edges getting deleted and re-added, eg if someone clicks "unfollow" and then "follow" again

**Comment by pfraze** [comment]
ready to npm publish at `1.3.0`

**Comment by dominictarr** [comment]
@pfraze hey I added you as npm owner so you can publish this.
please use `npm version {patch, minor, major}` so that version bump is in it's own commit and it's easy to reconcile npm and git. Okay, back on the road!

**Comment by pfraze** [comment]
ok cool, i've been doing that manually before now. thx!

**Pull request merged**
